<a href="https://colab.research.google.com/github/AliArabi55/iTi-AI-Task/blob/add-notebook-solution/DataPrep_assigment(Day3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Library**

In [232]:
import pandas as pd
import numpy as np

# **Load Data**

In [233]:
df=pd.read_csv("/content/DataPrep_assig2_data.csv")
# Display
df.head()

,Unnamed: 0,id,age,gender,income,days_on_platform,city,purchases
0,0,0,NaN,Male,126895,14.0,San Francisco,0
1,1,1,NaN,Male,161474,14.0,Tokyo,0
2,2,2,24.0,Male,104723,34.0,London,1
3,3,3,29.0,Male,43791,28.0,London,2
4,4,4,18.0,Female,132181,26.0,London,2

# **Data Preperation**

#Dataframe information before preprocessing

In [234]:
# Print information about the DataFrame before preprocessing
print(f"number of rows: {df.shape[0]}\nnumber of columns: {df.shape[1]}")

number of rows: 5000
number of columns: 8

In [235]:
# Display descriptive statistics of the DataFrame
print(df.describe().T)

                   count          mean           std   min       25%      50%  \
Unnamed: 0        5000.0   2499.500000   1443.520003   0.0   1249.75   2499.5
id                5000.0   2499.500000   1443.520003   0.0   1249.75   2499.5
age               2554.0     30.202036     12.129439  10.0     19.00     30.0
income            5000.0  79593.336200  60304.056095   4.0  32752.50  65989.0
days_on_platform  4859.0     24.389998     18.153388   1.0     10.00     21.0
purchases         5000.0      1.101000      1.181473   0.0      0.00      1.0

                        75%       max
Unnamed: 0          3749.25    4999.0
id                  3749.25    4999.0
age                   41.00      50.0
income            115406.50  388572.0
days_on_platform      35.00     111.0
purchases              2.00       6.0

In [236]:
# Print the number of null values in each column and the sum of duplicates
print(f"null values in each column:\n\n{df.isnull().sum()}\n\nSum of duplicates: {df.duplicated().sum()}")

null values in each column:

Unnamed: 0             0
id                     0
age                 2446
gender                 0
income                 0
days_on_platform     141
city                   0
purchases              0
dtype: int64

Sum of duplicates: 0

In [237]:
# Print the data types of each column
print(f"data types:\n\n{df.dtypes}")

data types:

Unnamed: 0            int64
id                    int64
age                 float64
gender               object
income                int64
days_on_platform    float64
city                 object
purchases             int64
dtype: object

In [238]:
df=df.drop(['Unnamed: 0'],axis=1)
df.head()

   id   age  gender  income  days_on_platform           city  purchases
0   0   NaN    Male  126895              14.0  San Francisco          0
1   1   NaN    Male  161474              14.0          Tokyo          0
2   2  24.0    Male  104723              34.0         London          1
3   3  29.0    Male   43791              28.0         London          2
4   4  18.0  Female  132181              26.0         London          2


# **Handle Missing Values**

In [239]:
# Fill missing values in the 'age' column with the mean
df['age'].fillna(df['age'].mean(), inplace=True)

# Drop rows with missing values in other columns
df.dropna(inplace=True)

print(df.head())

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036    Male  126895              14.0  San Francisco          0
1   1  30.202036    Male  161474              14.0          Tokyo          0
2   2  24.000000    Male  104723              34.0         London          1
3   3  29.000000    Male   43791              28.0         London          2
4   4  18.000000  Female  132181              26.0         London          2


# **Handle Duplicates**

In [240]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)
print(df.head())

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036    Male  126895              14.0  San Francisco          0
1   1  30.202036    Male  161474              14.0          Tokyo          0
2   2  24.000000    Male  104723              34.0         London          1
3   3  29.000000    Male   43791              28.0         London          2
4   4  18.000000  Female  132181              26.0         London          2

# **Data Transformation**

In [241]:
# Convert 'gender' to a categorical variable
df['gender'] = df['gender'].astype('category')

# Convert 'city' to a categorical variable
df['city'] = df['city'].astype('category')

print(df.head())

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036    Male  126895              14.0  San Francisco          0
1   1  30.202036    Male  161474              14.0          Tokyo          0
2   2  24.000000    Male  104723              34.0         London          1
3   3  29.000000    Male   43791              28.0         London          2
4   4  18.000000  Female  132181              26.0         London          2

# **Encoding**

In [242]:
df["city"].unique()

['San Francisco', 'Tokyo', 'London', 'New York City', 'Miami']
Categories (5, object): ['London', 'Miami', 'New York City', 'San Francisco', 'Tokyo']

In [243]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.25.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.1)

In [244]:
import category_encoders as ce
# create object of Ordinalencoding
encoder= ce.OrdinalEncoder(cols=['gender'], return_df=True,mapping=[{'col': 'gender', 'mapping': {'Male': 1, 'Female': 0}}])  # Map 'gender'

In [245]:
df_train_transformed = encoder.fit_transform(df)
df_train_transformed.head()

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036       1  126895              14.0  San Francisco          0
1   1  30.202036       1  161474              14.0          Tokyo          0
2   2  24.000000       1  104723              34.0         London          1
3   3  29.000000       1   43791              28.0         London          2
4   4  18.000000       0  132181              26.0         London          2

In [246]:
#Create object for one-hot encoding
encoder=ce.OneHotEncoder(cols='city',return_df=True)

df_train_transformed=encoder.fit_transform(df_train_transformed)
df_train_transformed.head()

,id,age,gender,income,days_on_platform,city_1,city_2,city_3,city_4,city_5,purchases
0,0,30.202036,1,126895,14.0,1,0,0,0,0,0
1,1,30.202036,1,161474,14.0,0,1,0,0,0,0
2,2,24.000000,1,104723,34.0,0,0,1,0,0,1
3,3,29.000000,1,43791,28.0,0,0,1,0,0,2
4,4,18.000000,0,132181,26.0,0,0,1,0,0,2

## **sklearn**

In [247]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [248]:
#Copy from Data
df_copy = df_train_transformed.copy()

imputer = IterativeImputer(max_iter=5, random_state=42)
imputed_data = imputer.fit_transform(df_copy)
imputed_df = pd.DataFrame(imputed_data, columns=df_copy.columns)
df_copy.iloc[:, :] = imputed_data

In [249]:
# Now you can use df_copy.head()
df_copy.head()

,id,age,gender,income,days_on_platform,city_1,city_2,city_3,city_4,city_5,purchases
0,0,30.202036,1,126895,14.0,1,0,0,0,0,0
1,1,30.202036,1,161474,14.0,0,1,0,0,0,0
2,2,24.000000,1,104723,34.0,0,0,1,0,0,1
3,3,29.000000,1,43791,28.0,0,0,1,0,0,2
4,4,18.000000,0,132181,26.0,0,0,1,0,0,2

In [250]:
df.head()

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036    Male  126895              14.0  San Francisco          0
1   1  30.202036    Male  161474              14.0          Tokyo          0
2   2  24.000000    Male  104723              34.0         London          1
3   3  29.000000    Male   43791              28.0         London          2
4   4  18.000000  Female  132181              26.0         London          2

# **Data Exploration**

In [251]:
# Applying a condition to replace values
df_copy['Instractur'] = np.where(df_copy['age'] > 45, 'teach', 'not teach')

# Display the updated dataframe
df_copy.head()

,id,age,gender,income,days_on_platform,city_1,city_2,city_3,city_4,city_5,purchases,Instractur
0,0,30.202036,1,126895,14.0,1,0,0,0,0,0,not teach
1,1,30.202036,1,161474,14.0,0,1,0,0,0,0,not teach
2,2,24.000000,1,104723,34.0,0,0,1,0,0,1,not teach
3,3,29.000000,1,43791,28.0,0,0,1,0,0,2,not teach
4,4,18.000000,0,132181,26.0,0,0,1,0,0,2,not teach

In [252]:
def calculate_bouns(data):
  if data["age"] > 45:
    return data["income"]*0.1
  else:
    return data["income"]*0.05

In [253]:
df_copy["bouns"]=df_copy.apply(calculate_bouns,axis=1)
df_copy.head()

,id,age,gender,income,days_on_platform,city_1,city_2,city_3,city_4,city_5,purchases,Instractur,bouns
0,0,30.202036,1,126895,14.0,1,0,0,0,0,0,not teach,6344.75
1,1,30.202036,1,161474,14.0,0,1,0,0,0,0,not teach,8073.70
2,2,24.000000,1,104723,34.0,0,0,1,0,0,1,not teach,5236.15
3,3,29.000000,1,43791,28.0,0,0,1,0,0,2,not teach,2189.55
4,4,18.000000,0,132181,26.0,0,0,1,0,0,2,not teach,6609.05

In [254]:
df.head()

   id        age  gender  income  days_on_platform           city  purchases
0   0  30.202036    Male  126895              14.0  San Francisco          0
1   1  30.202036    Male  161474              14.0          Tokyo          0
2   2  24.000000    Male  104723              34.0         London          1
3   3  29.000000    Male   43791              28.0         London          2
4   4  18.000000  Female  132181              26.0         London          2

In [255]:
# Creating a pivot table
pivot_table = df.pivot_table(index='city', columns='gender', values='income', aggfunc='sum')

# Display the pivot table
print("\nPivot Table:")
pivot_table

Pivot Table:

gender           Female      Male
city
London         34921981  40177740
Miami          38212698  39436978
New York City  38969149  40561787
San Francisco  39241979  36828683
Tokyo          38783551  39950141